package config

// Hotfix for v0.8.8.1: substitute `@varname` placeholders in
// `parser_config.outbounds[].options` (and `parser_config.proxies[].outbounds[].options`)
// before the parser hands them to sing-box. The bug shipped in v0.8.7 (SPEC 040)
// when auto-proxy-out URLTest options were templated as `@urltest_url /
// @urltest_interval / @urltest_tolerance`, but no code path actually replaced
// those placeholders for selectors generated by the parser — sing-box then
// failed `outbounds[1].interval: time: invalid duration "@urltest_interval"`.
//
// The proper fix (typed event-bus + state/config decoupling) lives on the
// SPEC 045/046/047 line. This file is a self-contained patch:
//
//   1. Walk every option that is a string starting with `@`.
//   2. Resolve via the supplied substituter (built from disk: wizard_template.json
//      vars + state.json settings_vars).
//   3. If the substituter is nil or doesn't know the name, fall back to a
//      tiny hard-coded table for the three URLTest placeholders introduced
//      in v0.8.7. Defense-in-depth for users whose state.json or template
//      went sideways.
//   4. Otherwise leave the placeholder alone — better to ship something
//      sing-box rejects loudly than to silently misconfigure.
//
// Users with a "broken" state.json from v0.8.7+ are healed transparently:
// the placeholder text remains in `parser_config` (where the wizard editor
// surfaces it as a template reference), but the generated outbound JSON
// fed to sing-box has the resolved value.

import (
	"encoding/json"
	"os"
	"strconv"
	"strings"

	"singbox-launcher/internal/debuglog"
	"singbox-launcher/internal/platform"
)

// VarSubstituter resolves a single `@name` placeholder. Returns the resolved
// value (string / int / bool) and ok=true on success. ok=false signals the
// caller to fall through to the hard-coded fallback table.
type VarSubstituter func(name string) (interface{}, bool)

// SubstituteParserConfigPlaceholders walks every `Options` map under
// `parserConfig` and replaces string values that look like `@name` with
// resolved values. Modifies the maps in place. Safe on nil parserConfig.
func SubstituteParserConfigPlaceholders(parserConfig *ParserConfig, subst VarSubstituter) {
	if parserConfig == nil {
		return
	}
	for i := range parserConfig.ParserConfig.Outbounds {
		substituteOptionsMap(parserConfig.ParserConfig.Outbounds[i].Options, subst, parserConfig.ParserConfig.Outbounds[i].Tag)
	}
	for pi := range parserConfig.ParserConfig.Proxies {
		for oi := range parserConfig.ParserConfig.Proxies[pi].Outbounds {
			substituteOptionsMap(parserConfig.ParserConfig.Proxies[pi].Outbounds[oi].Options, subst, parserConfig.ParserConfig.Proxies[pi].Outbounds[oi].Tag)
		}
	}
}

func substituteOptionsMap(options map[string]interface{}, subst VarSubstituter, ownerTag string) {
	if options == nil {
		return
	}
	for k, v := range options {
		s, ok := v.(string)
		if !ok || !strings.HasPrefix(s, "@") {
			continue
		}
		name := strings.TrimPrefix(s, "@")
		if name == "" || strings.Contains(name, "@") {
			continue
		}
		if subst != nil {
			if val, ok := subst(name); ok {
				options[k] = val
				continue
			}
		}
		if val, ok := knownPlaceholderFallback(name); ok {
			options[k] = val
			debuglog.WarnLog("varsubst: outbound %q option %q: @%s resolved via built-in fallback", ownerTag, k, name)
			continue
		}
		debuglog.WarnLog("varsubst: outbound %q option %q: unresolved placeholder @%s left as literal — sing-box will likely reject this", ownerTag, k, name)
	}
}

// knownPlaceholderFallback returns hard-coded defaults for the three URLTest
// placeholders introduced in SPEC 040 (v0.8.7). These match v0.8.6 behavior
// before the placeholders were introduced, so users who upgraded from
// v0.8.6 with no other state changes get consistent behavior even if their
// state.json / template disappeared. Any other unknown placeholder returns
// ok=false — the caller leaves the literal in place and logs a warning.
func knownPlaceholderFallback(name string) (interface{}, bool) {
	switch name {
	case "urltest_url":
		return "https://cp.cloudflare.com/generate_204", true
	case "urltest_interval":
		return "5m", true
	case "urltest_tolerance":
		// sing-box expects a number for tolerance, not a string.
		return 100, true
	}
	return nil, false
}

// BuildVarSubstituterFromDisk reads the wizard template and state files via
// canonical path helpers (platform.GetWizardTemplatePath /
// GetWizardStatePath) and returns a VarSubstituter that resolves `@name`
// placeholders against them.
//
// Resolution order per name:
//  1. `state.json` settings_vars override (user choice from Settings tab).
//  2. `wizard_template.json` `vars[].default_value` matching `name`.
//  3. ok=false → caller falls back to `knownPlaceholderFallback`.
//
// Type coercion: a few well-known integer-valued vars (e.g. `urltest_tolerance`,
// `tun_mtu`, `*_listen_port`) are converted from string to int so JSON
// marshalling produces a number. Booleans (declared `type:"bool"`) are
// likewise coerced. Everything else stays string.
//
// Failure to read either file is non-fatal — substituter then knows nothing
// and the caller falls through to the hard-coded URLTest fallback.
func BuildVarSubstituterFromDisk(execDir string) VarSubstituter {
	defaults := loadTemplateVarDefaults(execDir)
	overrides := loadStateSettingsVars(execDir)
	intVars := intCastVarNames()
	boolVars := defaults.boolNames

	return func(name string) (interface{}, bool) {
		// 1. settings_vars override (string → typed)
		if v, ok := overrides[name]; ok {
			return coerceVarValue(name, v, intVars, boolVars), true
		}
		// 2. template default_value
		if v, ok := defaults.values[name]; ok {
			return coerceVarValue(name, v, intVars, boolVars), true
		}
		return nil, false
	}
}

type templateVarDefaults struct {
	values    map[string]string // name → default_value (string form)
	boolNames map[string]struct{}
}

// loadTemplateVarDefaults reads only what we need from wizard_template.json:
// the `vars` array. Each var contributes its `default_value` (in string
// form — for object form per-platform default we pick `"default"` first,
// else current GOOS, else any). Type "bool" tracked for coercion.
//
// Robust to missing file / parse errors — returns empty maps and lets the
// caller fall through to defaults.
func loadTemplateVarDefaults(execDir string) templateVarDefaults {
	out := templateVarDefaults{
		values:    map[string]string{},
		boolNames: map[string]struct{}{},
	}
	path := platform.GetWizardTemplatePath(execDir)
	raw, err := os.ReadFile(path)
	if err != nil {
		debuglog.DebugLog("varsubst: cannot read %s: %v", path, err)
		return out
	}
	var root struct {
		Vars []json.RawMessage `json:"vars"`
	}
	if err := json.Unmarshal(raw, &root); err != nil {
		debuglog.DebugLog("varsubst: cannot parse %s: %v", path, err)
		return out
	}
	for _, vRaw := range root.Vars {
		var v struct {
			Name         string          `json:"name"`
			Type         string          `json:"type"`
			Separator    bool            `json:"separator"`
			DefaultValue json.RawMessage `json:"default_value"`
		}
		if err := json.Unmarshal(vRaw, &v); err != nil {
			continue
		}
		if v.Separator || v.Name == "" {
			continue
		}
		if v.Type == "bool" {
			out.boolNames[v.Name] = struct{}{}
		}
		if defStr, ok := readVarDefaultValue(v.DefaultValue); ok {
			out.values[v.Name] = defStr
		}
	}
	return out
}

// readVarDefaultValue extracts a string default from `default_value`. Accepts:
//   - bare string: `"foo"`
//   - bare number: `5`
//   - bare bool: `true`
//   - object: `{"darwin":"a","windows":"b","default":"c"}` — picks `default` if
//     present, else any value (we don't have the user's GOOS in this layer
//     and don't need precision; URLTest defaults aren't platform-specific).
func readVarDefaultValue(raw json.RawMessage) (string, bool) {
	if len(raw) == 0 || string(raw) == "null" {
		return "", false
	}
	var s string
	if err := json.Unmarshal(raw, &s); err == nil {
		return s, true
	}
	var n json.Number
	if err := json.Unmarshal(raw, &n); err == nil {
		return n.String(), true
	}
	var b bool
	if err := json.Unmarshal(raw, &b); err == nil {
		if b {
			return "true", true
		}
		return "false", true
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(raw, &obj); err == nil {
		if v, ok := obj["default"]; ok {
			return readVarDefaultValue(v)
		}
		for _, v := range obj {
			return readVarDefaultValue(v)
		}
	}
	return "", false
}

// loadStateSettingsVars reads `settings_vars` from the wizard state file.
// Layout matches WizardStateFile in ui/wizard/models/wizard_state_file.go:
// settings_vars is a JSON array of {name, value} objects, NOT a map.
//
// Path resolution: platform.GetWizardStatePath — the canonical
// <execDir>/bin/wizard_states/state.json. Do not hard-code this.
//
// Robust to missing file / parse errors — returns empty map and lets the
// caller fall through to template defaults / hard-coded fallback.
func loadStateSettingsVars(execDir string) map[string]string {
	out := map[string]string{}
	path := platform.GetWizardStatePath(execDir)
	raw, err := os.ReadFile(path)
	if err != nil {
		debuglog.DebugLog("varsubst: cannot read %s: %v", path, err)
		return out
	}
	var root struct {
		// settings_vars is the canonical key (snake_case via the SettingVar
		// JSON tag); SettingsVars is also accepted for older files that
		// happened to be saved before the tag was added.
		SettingsVarsSnake []settingVarEntry `json:"settings_vars"`
		SettingsVarsCamel []settingVarEntry `json:"SettingsVars"`
	}
	if err := json.Unmarshal(raw, &root); err != nil {
		debuglog.DebugLog("varsubst: cannot parse %s: %v", path, err)
		return out
	}
	entries := root.SettingsVarsSnake
	if len(entries) == 0 {
		entries = root.SettingsVarsCamel
	}
	for _, e := range entries {
		if e.Name == "" || e.Value == "" {
			continue
		}
		out[e.Name] = e.Value
	}
	return out
}

// settingVarEntry mirrors the SettingVar struct in ui/wizard/models — kept
// local to avoid importing the ui-side package from core/config.
type settingVarEntry struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// intCastVarNames is the canonical set of vars that ship as JSON numbers in
// the final config. Mirrors `ui/wizard/template/substitute.go isIntCastVar`
// — kept in sync manually to avoid an import cycle.
func intCastVarNames() map[string]struct{} {
	return map[string]struct{}{
		"tun_mtu":              {},
		"mixed_listen_port":    {},
		"proxy_in_listen_port": {},
		"urltest_tolerance":    {},
	}
}

// coerceVarValue decides the runtime type of a substituted var based on its
// name. Strings stay strings; ints declared in intVars are parsed as numbers;
// bools declared in boolVars become true/false.
func coerceVarValue(name, value string, intVars, boolVars map[string]struct{}) interface{} {
	if _, isBool := boolVars[name]; isBool {
		return strings.EqualFold(strings.TrimSpace(value), "true")
	}
	if _, isInt := intVars[name]; isInt {
		if n, err := strconv.Atoi(strings.TrimSpace(value)); err == nil {
			return n
		}
		debuglog.WarnLog("varsubst: var %q expected int, got %q — passing through as string", name, value)
		return value
	}
	return value
}
